[tool.poetry]
name = "chess"
version = "0.1.0"
description = ""
authors = ["Mafalda Martinho"]
packages = [{ include = "chess"}]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.11"
numpy = ">=1.26.4"
fastapi = {extras = ["standard"], version = "^0.136.3"}
requests = "^2.34.2"
snakeviz = "^2.2.2"
pytest = "^9.1.1"
psycopg2 = "^2.9.12"
pydantic = "^2.13.4"
sqlalchemy = "^2.0.51"
psycopg2-binary = "^2.9.12"
ruff = "^0.15.21"

[build.system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"