[tool.poetry]
name = "chess"
version = "0.1.0"
description = ""
authors = ["Mafalda Martinho"]
packages = [{ include = "chess"}]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.11"
numpy = ">=1.26.4"
fastapi = "^0.136.3"

[build.system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"