name: CI

on:
  push:
  pull_request:
    branches:
      - main

jobs:
  ruff:
    name: Ruff
    runs-on: ubuntu-latest

    steps:
      - name: Download repository
        uses: actions/checkout@v5

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.11"

      - name: Install Poetry
        run: pip install poetry

      - name: Install dependencies
        run: poetry install

      - name: Check linting
        run: poetry run ruff check .

      - name: Check formatting
        run: poetry run ruff format --check .


  mypy:
    name: Mypy
    runs-on: ubuntu-latest

    steps:
      - name: Download repository
        uses: actions/checkout@v5

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.11"

      - name: Install Poetry
        run: pip install poetry

      - name: Install dependencies
        run: poetry install

      - name: Check types
        run: poetry run mypy chess


  pytest:
    name: Pytest
    runs-on: ubuntu-latest

    steps:
      - name: Download repository
        uses: actions/checkout@v5

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.11"

      - name: Install Poetry
        run: pip install poetry

      - name: Install dependencies
        run: poetry install

      - name: Run tests
        run: poetry run pytest